import os

CONNECTION = os.getenv("SNOWFLAKE_CONNECTION")
ROLE_NAME = os.getenv("SNOWFLAKE_ROLE") or "EXTERNAL_SNOWFLAKE_ARCHITECTS"
DB_NAME = os.getenv("SNOWFLAKE_DATABASE") or "ML_COLLAB_DEV_DB"
SCHEMA_NAME = os.getenv("SNOWFLAKE_SCHEMA") or "SANDBOX"
ENVIRONMENT = os.getenv("SNOWFLAKE_ENVIRONMENT") or "DEV"

BUILD_STAGE = f"{DB_NAME}.{SCHEMA_NAME}.BUILD_STAGE"
JOB_STAGE = f"{DB_NAME}.{SCHEMA_NAME}.JOB_STAGE"

#FEATURE_STORE_NAME = os.getenv("FEATURE_STORE_NAME") or f"{DB_NAME}.DATA"
