import os

ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
USER = os.getenv("SNOWFLAKE_USER")
PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
DB_NAME = os.getenv("SNOWFLAKE_DATABASE") or "ML_COLLAB_DEV_DB"
MODEL_SCHEMA = os.getenv("SNOWFLAKE_MODEL_SCHEMA") or "SANDBOX"
FEATURE_SCHEMA = os.getenv("SNOWFLAKE_FEATURE_SCHEMA") or "SANDBOX"
ENVIRONMENT = os.getenv("SNOWFLAKE_ENVIRONMENT") or "DEV"

BUILD_STAGE = f"{DB_NAME}.{MODEL_SCHEMA}.BUILD_STAGE"
JOB_STAGE = f"{DB_NAME}.{MODEL_SCHEMA}.JOB_STAGE"