# will need to have all elements needed to set up
deploy:
  pipelines:
    - file: training.ipynb
      schedule: None
    - file: inference.ipynb
      schedule: None

N_FEATURES: 5
N_SAMPLES_TRAIN: 1000
N_SAMPLES_INFER: 100