# will need to have all elements needed to set up
project_name: example_project
active: True

deploy:
  warehouse:
    warehouse_size: SMALL
    auto_suspend: 300
  compute_pool:
    instance_family: CPU_X64_XS
    #max_nodes: 3

  DAGS:
    - name: EXAMPLE1
      tasks:
        - name: training
          file: training.ipynb
      schedule: CRON 30 3 * * * UTC
    - name: EXAMPLE2
      tasks:
        - name: inference
          file: inference.py
      schedule: 3 HOURS
    - name: EXAMPLE3
      tasks:
        - name: prepare
          file: prepare_data.py
        - name: train
          file: training.py
          mljob: True
          #target_instances: 3
          dep: prepare
        - name: promote
          file: promote_model.py
          dep: train
      schedule: