import os

CONNECTION = os.getenv("SNOWFLAKE_CONNECTION")
ROLE_NAME = os.getenv("SNOWFLAKE_ROLE") or "EXTERNAL_SNOWFLAKE_ARCHITECTS"
DB_NAME = os.getenv("SNOWFLAKE_DATABASE") or "ML_COLLAB_DEV_DB"
SCHEMA_NAME = os.getenv("SNOWFLAKE_SCHEMA") or "SANDBOX"
WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE") or "SNOWPARK_WAREHOUSE"
COMPUTE_POOL = os.getenv("SNOWFLAKE_COMPUTE_POOL") or "ML_TESTING_POOL"

GIT_STAGE = f"{DB_NAME}.{SCHEMA_NAME}.GIT_STAGE"
JOB_STAGE = f"{DB_NAME}.{SCHEMA_NAME}.JOB_STAGE"

#FEATURE_STORE_NAME = os.getenv("FEATURE_STORE_NAME") or f"{DB_NAME}.DATA"
