import os

CONNECTION = os.getenv("SNOWFLAKE_CONNECTION")
ROLE_NAME = os.getenv("SNOWFLAKE_ROLE") or "EXTERNAL_SNOWFLAKE_ARCHITECTS"
DB_NAME = os.getenv("SNOWFLAKE_DATABASE") or "ML_COLLAB_DEV_DB"
SCHEMA_NAME = os.getenv("SNOWFLAKE_SCHEMA") or "SANDBOX"
WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE") or "SNOWPARK_WAREHOUSE"
GIT_STAGE = os.getenv("SNOWFLAKE_GIT_REPO") or "GIT_STAGE"
#COMPUTE_POOL = os.getenv("SNOWFLAKE_COMPUTE_POOL") or "DEMO_POOL"

#GIT_STAGE = f"@{DB_NAME}.{SCHEMA_NAME}."
#JOB_STAGE = f"@{DB_NAME}.{SCHEMA_NAME}.JOB_STAGE"

#FEATURE_STORE_NAME = os.getenv("FEATURE_STORE_NAME") or f"{DB_NAME}.DATA"
