# will need to have all elements needed to set up
project_name: project_template

deploy:
  DAGS:
    - name: training
      tasks:
        - name: training
          file: training.py
        - name: beep
          file: beep.py
          dep: training
        - name: boop
          file: boop.py
          dep: training
        - name: inference
          file: inference.ipynb
          dep: 
            - beep
            - boop  
        - name: final
          file: blorp.py
          final: True 
      schedule: 

N_FEATURES: 5
N_SAMPLES_TRAIN: 1000
N_SAMPLES_INFER: 100