# will need to have all elements needed to set up
project_name: project_template

deploy:
  DAGS:
    - name: training
      tasks:
        - name: training
          file: training.py
          mljob: True
        - name: promote_model
          file: promote_model.py
          dep: training
        - name: create_monitor
          file: create_monitor.py
          dep: training
        - name: inference
          file: inference.ipynb
          dep: 
            - promote_model
            - create_monitor  
        - name: cleanup
          file: cleanup.py
          final: True 
      schedule: 

N_FEATURES: 5
N_SAMPLES_TRAIN: 1000
N_SAMPLES_INFER: 100