USE ROLE ACCOUNTADMIN;

SET USERNAME = (SELECT CURRENT_USER());

CREATE ROLE IF NOT EXISTS ML_PIPELINE_<% env %>_ROLE;

GRANT CREATE DATABASE on ACCOUNT to ROLE ML_PIPELINE_<% env %>_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ML_PIPELINE_<% env %>_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE ML_PIPELINE_<% env %>_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ML_PIPELINE_<% env %>_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE ML_PIPELINE_<% env %>_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE ML_PIPELINE_<% env %>_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE ML_PIPELINE_<% env %>_ROLE;

GRANT ROLE ML_PIPELINE_<% env %>_ROLE TO USER identifier($USERNAME);

USE ROLE ML_PIPELINE_<% env %>_ROLE;

CREATE DATABASE IF NOT EXISTS ML_PIPELINE_<% env %>_DB;
USE DATABASE ML_PIPELINE_<% env %>_DB;

CREATE SCHEMA IF NOT EXISTS BASE_DATA;
CREATE SCHEMA IF NOT EXISTS ML_PROJECTS;

CREATE STAGE IF NOT EXISTS BASE_DATA.DATA_STAGE
    DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS ML_PROJECTS.BUILD_STAGE
    DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS ML_PROJECTS.JOB_STAGE
    DIRECTORY = (ENABLE = TRUE);

CREATE WAREHOUSE IF NOT EXISTS ML_PIPELINE_<% env %>_XS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE SCHEMA BASE_DATA;
USE WAREHOUSE ML_PIPELINE_<% env %>_XS_WH;

USE ROLE ACCOUNTADMIN;

CREATE NETWORK POLICY IF NOT EXISTS AUTOMATION_ACCESS_POLICY
    ALLOWED_NETWORK_RULE_LIST = ("SNOWFLAKE.NETWORK_SECURITY.GITHUBACTIONS_GLOBAL");

CREATE USER IF NOT EXISTS GIT_ACTIONS_<% env %>
    DEFAULT_ROLE = ML_PIPELINE_<% env %>_ROLE
    DEFAULT_WAREHOUSE = ML_PIPELINE_<% env %>_XS_WH
    NETWORK_POLICY = AUTOMATION_ACCESS_POLICY
    TYPE = SERVICE;

GRANT ROLE ML_PIPELINE_<% env %>_ROLE TO USER GIT_ACTIONS_<% env %>;

USE ROLE ML_PIPELINE_<% env %>_ROLE;

PUT file://setup/MORTGAGE_LENDING_DEMO_DATA.csv.gz @DATA_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = 'AUTO';

CREATE OR REPLACE TABLE MORTGAGE_LENDING_DEMO_DATA
    USING TEMPLATE (
        SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
        FROM TABLE(
            INFER_SCHEMA(
                LOCATION => '@DATA_STAGE',
                FILE_FORMAT => 'CSV_FORMAT'
            )
        )
    );

COPY INTO MORTGAGE_LENDING_DEMO_DATA
FROM @DATA_STAGE
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = 'AUTO' PARSE_HEADER = TRUE)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';